import { MCPServer } from '../mcp-server';
import { formatForClaudeVision, MCPContent } from '../comparison/report';

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

let capturer: any = null;
export function setCrossViewportCapture(c: any): void {
  capturer = c;
}

export function registerCrossViewportCompareTool(server: MCPServer): void {
  server.registerTool(
    {
      name: 'cross_viewport_compare',
      description:
        'Capture the same page across all active simulators for visual comparison. Returns screenshots with device/viewport/breakpoint metadata.',
      inputSchema: {
        type: 'object' as const,
        properties: {
          url: { type: 'string', description: 'URL to capture on all devices' },
          waitUntil: { type: 'string', enum: ['load', 'domcontentloaded', 'networkidle'] },
          settleTime: { type: 'number', description: 'Ms to wait after load for dynamic content' },
          format: { type: 'string', enum: ['default', 'html'], description: 'Output format (default: vision-optimized)' },
        },
        required: ['url'],
      },
    },
    async (_sessionId: string, params: Record<string, unknown>) => {
      if (!capturer)
        return { content: [{ type: 'text' as const, text: 'Error: Cross-viewport capture not initialized' }], isError: true };
      const captures = await capturer.capture(params.url as string, {
        waitUntil: params.waitUntil as any,
        settleTime: params.settleTime as number | undefined,
      });

      if (params.format === 'html') {
        const fsPromises = await import('fs/promises');
        const pathMod = await import('path');
        const osMod = await import('os');

        const deviceSections = captures
          .map((cap: any) => {
            const screenshotImg = cap.screenshot
              ? `<img src="data:image/png;base64,${cap.screenshot}" style="max-width:100%;border:1px solid #e5e7eb;border-radius:8px;" />`
              : '<p style="color:#6b7280;">No screenshot available</p>';
            return `<div style="flex:1;min-width:280px;"><h3 style="font-size:14px;font-weight:600;margin-bottom:8px;">${escapeHtml(String(cap.device ?? 'Unknown'))} (${cap.viewport?.w ?? '?'}x${cap.viewport?.h ?? '?'})</h3>${screenshotImg}</div>`;
          })
          .join('');

        const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Cross-Viewport Comparison - ${escapeHtml(String(params.url))}</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9fafb;color:#111827;line-height:1.5}.container{max-width:1200px;margin:0 auto;padding:32px 24px}h1{font-size:24px;font-weight:700;margin-bottom:8px}.devices{display:flex;gap:24px;flex-wrap:wrap;margin-top:16px}.footer{margin-top:48px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;text-align:center}</style>
</head><body><div class="container">
<h1>Cross-Viewport Comparison</h1>
<p style="color:#6b7280;margin-bottom:24px;">URL: ${escapeHtml(String(params.url))}</p>
<div class="devices">${deviceSections}</div>
<div class="footer">Generated by OpenSafari &middot; ${new Date().toISOString()}</div>
</div></body></html>`;

        const outputDir = pathMod.join(osMod.homedir(), '.opensafari', 'reports', 'html');
        await fsPromises.mkdir(outputDir, { recursive: true });
        const filename = `compare-${new Date().toISOString().replace(/[:.]/g, '-')}.html`;
        const filePath = pathMod.join(outputDir, filename);
        await fsPromises.writeFile(filePath, html, 'utf-8');

        return { content: [{ type: 'text' as const, text: `HTML comparison report saved to: ${filePath}` }] };
      }

      const content = formatForClaudeVision(captures);
      return {
        content: content.map((c: MCPContent) => ({
          type: (c.type ?? 'text') as 'text',
          text: c.text,
          ...(c.data ? { data: c.data, mimeType: c.mimeType } : {}),
        })),
      };
    },
  );
}
