import { MCPServer } from '../mcp-server';
import { collectHostBundle, clickHostPoint, dumpHostTree, hostScreenshot, launchHostApp, pressHostElement, queryHostTree } from '../macos/host-ax';
import { pressTestFlightAction, snapshotTestFlight, testFlightExists } from '../macos/testflight';

const ok = (x: unknown) => ({ content: [{ type: 'text' as const, text: JSON.stringify(x, null, 2) }] });
const err = (e: unknown) => ({ content: [{ type: 'text' as const, text: `Error: ${e instanceof Error ? e.message : String(e)}` }], isError: true });
const target = (p: Record<string, unknown>) => ({ bundleId: p.bundleId as string | undefined, processName: p.processName as string | undefined });

export function registerMacHostTools(server: MCPServer): void {
  server.registerTool({ name: 'mac_app_launch', description: 'Launch/foreground a host macOS app by bundleId or path. Does not require a simulator deviceId.', inputSchema: { type: 'object', properties: { bundleId: { type: 'string' }, path: { type: 'string' }, waitMs: { type: 'number' } }, required: [] } }, async (_s, p) => { try { return ok(await launchHostApp({ bundleId: p.bundleId as string | undefined, path: p.path as string | undefined, waitMs: p.waitMs as number | undefined })); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_app_tree', description: 'Dump a host macOS app Accessibility tree by bundleId or processName.', inputSchema: { type: 'object', properties: { bundleId: { type: 'string' }, processName: { type: 'string' }, maxDepth: { type: 'number' } }, required: [] } }, async (_s, p) => { try { return ok(await dumpHostTree({ ...target(p), maxDepth: p.maxDepth as number | undefined })); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_app_query', description: 'Query a host macOS app AX tree by identifier, label, text, or role.', inputSchema: { type: 'object', properties: { bundleId: { type: 'string' }, processName: { type: 'string' }, identifier: { type: 'string' }, label: { type: 'string' }, text: { type: 'string' }, role: { type: 'string' }, maxDepth: { type: 'number' } }, required: [] } }, async (_s, p) => { try { const tree = await dumpHostTree({ ...target(p), maxDepth: p.maxDepth as number | undefined }); const matches = queryHostTree(tree, { identifier: p.identifier as string | undefined, label: p.label as string | undefined, text: p.text as string | undefined, role: p.role as string | undefined }); return ok({ total: matches.length, matches }); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_app_tap_element', description: 'Press a host macOS AX element matching a query. Uses AXPress first; coordinate fallback only when allowCoordinateFallback is true.', inputSchema: { type: 'object', properties: { bundleId: { type: 'string' }, processName: { type: 'string' }, identifier: { type: 'string' }, label: { type: 'string' }, text: { type: 'string' }, role: { type: 'string' }, index: { type: 'number' }, allowCoordinateFallback: { type: 'boolean' }, maxDepth: { type: 'number' } }, required: [] } }, async (_s, p) => { try { const t = target(p); const tree = await dumpHostTree({ ...t, maxDepth: p.maxDepth as number | undefined }); const matches = queryHostTree(tree, { identifier: p.identifier as string | undefined, label: p.label as string | undefined, text: p.text as string | undefined, role: p.role as string | undefined }); const match = matches[(p.index as number | undefined) ?? 0]; if (!match) return ok({ ok: false, code: 'ELEMENT_NOT_FOUND', total: matches.length }); const pressed = await pressHostElement(t, match.path); if ((pressed as { ok?: boolean }).ok || !p.allowCoordinateFallback) return ok({ ...pressed, match, coordinateFallbackUsed: false }); const f = match.frame; const clicked = await clickHostPoint(f.x + f.width / 2, f.y + f.height / 2); return ok({ ...clicked, match, coordinateFallbackUsed: true }); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_app_screenshot', description: 'Capture a host macOS screenshot to an artifact path.', inputSchema: { type: 'object', properties: { artifactDir: { type: 'string' }, name: { type: 'string' } }, required: [] } }, async (_s, p) => { try { return ok({ screenshotPath: await hostScreenshot(p.artifactDir as string | undefined, p.name as string | undefined) }); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_app_context', description: 'Return host macOS app context with tree, matched query labels, and evidence paths when requested.', inputSchema: { type: 'object', properties: { bundleId: { type: 'string' }, processName: { type: 'string' }, artifactDir: { type: 'string' }, maxDepth: { type: 'number' }, queries: { type: 'array', items: { type: 'string' } } }, required: [] } }, async (_s, p) => { try { const tree = await dumpHostTree({ ...target(p), maxDepth: p.maxDepth as number | undefined }); const queries = (p.queries as string[] | undefined) ?? []; const found = Object.fromEntries(queries.map((q) => [q, queryHostTree(tree, { text: q }).length])); return ok({ tree, found, artifacts: p.artifactDir ? await collectHostBundle({ ...target(p), artifactDir: p.artifactDir as string, maxDepth: p.maxDepth as number | undefined }) : undefined }); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_debug_bundle_collect', description: 'Collect host macOS screenshot, AX tree, and cheap recent logs for an app.', inputSchema: { type: 'object', properties: { bundleId: { type: 'string' }, processName: { type: 'string' }, artifactDir: { type: 'string' }, maxDepth: { type: 'number' } }, required: [] } }, async (_s, p) => { try { return ok(await collectHostBundle({ ...target(p), artifactDir: p.artifactDir as string | undefined, maxDepth: p.maxDepth as number | undefined })); } catch (e) { return err(e); } });

  server.registerTool({ name: 'mac_testflight_snapshot', description: 'Launch-inspect host macOS TestFlight and classify account/app/build state without entering credentials.', inputSchema: { type: 'object', properties: { appName: { type: 'string' }, artifactDir: { type: 'string' } }, required: ['appName'] } }, async (_s, p) => { try { if (testFlightExists()) await launchHostApp({ bundleId: 'com.apple.TestFlight', waitMs: 1000 }); return ok(await snapshotTestFlight(String(p.appName), p.artifactDir as string | undefined)); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_testflight_find_build', description: 'Read-only alias of mac_testflight_snapshot for a named app/build.', inputSchema: { type: 'object', properties: { appName: { type: 'string' }, expectedBuildNumber: { type: 'string' }, artifactDir: { type: 'string' } }, required: ['appName'] } }, async (_s, p) => { try { if (testFlightExists()) await launchHostApp({ bundleId: 'com.apple.TestFlight', waitMs: 1000 }); const snap = await snapshotTestFlight(String(p.appName), p.artifactDir as string | undefined); return ok({ ...snap, expectedBuildNumber: p.expectedBuildNumber }); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_testflight_install_update_open', description: 'For host TestFlight, press Install/Update/Open only when that safe action is visible; credentials/2FA remain human blockers.', inputSchema: { type: 'object', properties: { appName: { type: 'string' }, artifactDir: { type: 'string' } }, required: ['appName'] } }, async (_s, p) => { try { if (testFlightExists()) await launchHostApp({ bundleId: 'com.apple.TestFlight', waitMs: 1000 }); const snap = await snapshotTestFlight(String(p.appName), p.artifactDir as string | undefined); if (!snap.tree) return ok(snap); const action = snap.state === 'INSTALL_AVAILABLE' ? 'Install' : snap.state === 'UPDATE_AVAILABLE' ? 'Update' : snap.state === 'OPEN_AVAILABLE' ? 'Open' : undefined; if (!action) return ok({ ...snap, actionTaken: false }); return ok({ ...snap, actionTaken: action, actionResult: await pressTestFlightAction(snap.tree, action) }); } catch (e) { return err(e); } });
  server.registerTool({ name: 'mac_testflight_qa_run', description: 'Minimal Omofictions-style host TestFlight QA recipe: snapshot TestFlight, install/update/open if safe, collect app AX/screenshot evidence for target labels. Purchase confirmation is human-gated unless allowPurchaseConfirm is true.', inputSchema: { type: 'object', properties: { appName: { type: 'string' }, expectedBundleId: { type: 'string' }, expectedBuildNumber: { type: 'string' }, artifactDir: { type: 'string' }, allowPurchaseConfirm: { type: 'boolean' } }, required: ['appName', 'expectedBundleId'] } }, async (_s, p) => { try { const artifactDir = p.artifactDir as string | undefined; const install = await (async () => { if (testFlightExists()) await launchHostApp({ bundleId: 'com.apple.TestFlight', waitMs: 1000 }); const snap = await snapshotTestFlight(String(p.appName), artifactDir); if (!snap.tree) return { snapshot: snap }; const action = snap.state === 'INSTALL_AVAILABLE' ? 'Install' : snap.state === 'UPDATE_AVAILABLE' ? 'Update' : snap.state === 'OPEN_AVAILABLE' ? 'Open' : undefined; return { snapshot: snap, action, actionResult: action ? await pressTestFlightAction(snap.tree, action) : undefined }; })(); await new Promise((r) => setTimeout(r, 2000)); const labels = ['Ducats Shop', 'Payment Page', 'confirm-payment', 'restore-purchases']; let appEvidence: unknown; try { appEvidence = await collectHostBundle({ bundleId: p.expectedBundleId as string, artifactDir, maxDepth: 10 }); } catch (e) { appEvidence = { blocker: 'APP_NOT_RUNNING_OR_AX_UNAVAILABLE', message: e instanceof Error ? e.message : String(e) }; } let found: Record<string, number> = {}; try { const tree = await dumpHostTree({ bundleId: p.expectedBundleId as string, maxDepth: 10 }); found = Object.fromEntries(labels.map((q) => [q, queryHostTree(tree, { text: q }).length])); } catch { /* evidence above carries blocker */ } return ok({ appName: p.appName, expectedBundleId: p.expectedBundleId, expectedBuildNumber: p.expectedBuildNumber, allowPurchaseConfirm: p.allowPurchaseConfirm === true, testflight: install, appEvidence, found, nextSafeAction: found['confirm-payment'] && !p.allowPurchaseConfirm ? 'Purchase confirm visible; rerun with allowPurchaseConfirm only if authorized.' : 'Review artifact bundle.' }); } catch (e) { return err(e); } });
}
